version: "3.9"
services:
  database:
    image: postgres
    restart: always
    volumes:
    - db-vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_project

  web:
    container_name: go_server
    build: .
    image: server
    restart: always
    ports:
      - 8081:8081
    volumes:
    - ./cmd/:/config
    command: ["-confile",  "/config/config.yaml"]
    depends_on:
      - database

volumes:
  db-vol:
