version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 33333:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_project

  web:
    container_name: go_server
    build: .
    image: server
    ports:
      - 8081:8081
    depends_on:
      - db
#volume + env var + arg -config
