version: "3.9"
services:
  accounts-db:
    image: postgres:14.4
    restart: always
    volumes:
    - ./migration/:/docker-entrypoint-initdb.d/
    - accounts:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounts
    ports:
      - 5432:5432

  web:
    build: .
    image: server
    restart: always
    ports:
      - 8080:8080
    volumes:
    - ./cmd/:/config
    - ./ui/form:/form
    command: ["-confile",  "/config/config.yaml"]
    depends_on:
      - accounts-db

volumes:
  accounts:
