serverHost: "localhost:8081"

dbUrl: "postgresql://postgres:postgres@database:5432/accounts?sslmode=disable"
front: "/form"

mail:
  host: "smtp.gmail.com"
  port: 587
  sender: "email sender <your@email.com>"
  user: "your@email.com"
  password: "yourEmailPassword"