serverHost: "localhost:8081"

dbUrl: "postgresql://postgres:password@database:5432/go_project?sslmode=disable"
form : "/form"

mail:
  host: "smtp.gmail.com"
  port: 587
  sender: "email sender <your@email.com>"
  user: "your@email.com"
  password: "yourEmailPassword"