serverHost: ":8080"

# should work without a port bcs all configured in doc-compose
dbUrl: "postgresql://postgres:postgres@accounts-db/accounts?sslmode=disable"
front: "/form"

mail:
  host: "smtp.gmail.com"
  port: 587
  sender: "email sender <your@email.com>"
  user: "your@email.com"
  password: "yourEmailPassword"